//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.13.2
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from ./Gramatica/Analizador.g4 by ANTLR 4.13.2

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

namespace analyzer {
using Antlr4.Runtime.Misc;
using Antlr4.Runtime.Tree;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete generic visitor for a parse tree produced
/// by <see cref="AnalizadorParser"/>.
/// </summary>
/// <typeparam name="Result">The return type of the visit operation.</typeparam>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.13.2")]
[System.CLSCompliant(false)]
public interface IAnalizadorVisitor<Result> : IParseTreeVisitor<Result> {
	/// <summary>
	/// Visit a parse tree produced by <see cref="AnalizadorParser.program"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitProgram([NotNull] AnalizadorParser.ProgramContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>PrintStmt</c>
	/// labeled alternative in <see cref="AnalizadorParser.dcl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPrintStmt([NotNull] AnalizadorParser.PrintStmtContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>IfStmt</c>
	/// labeled alternative in <see cref="AnalizadorParser.dcl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitIfStmt([NotNull] AnalizadorParser.IfStmtContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>WhileStmt</c>
	/// labeled alternative in <see cref="AnalizadorParser.dcl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitWhileStmt([NotNull] AnalizadorParser.WhileStmtContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>ForStmt</c>
	/// labeled alternative in <see cref="AnalizadorParser.dcl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitForStmt([NotNull] AnalizadorParser.ForStmtContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>SwitchStmt</c>
	/// labeled alternative in <see cref="AnalizadorParser.dcl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSwitchStmt([NotNull] AnalizadorParser.SwitchStmtContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>FuncDeclStmt</c>
	/// labeled alternative in <see cref="AnalizadorParser.dcl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFuncDeclStmt([NotNull] AnalizadorParser.FuncDeclStmtContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>BreakStmt</c>
	/// labeled alternative in <see cref="AnalizadorParser.dcl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitBreakStmt([NotNull] AnalizadorParser.BreakStmtContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>ContinueStmt</c>
	/// labeled alternative in <see cref="AnalizadorParser.dcl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitContinueStmt([NotNull] AnalizadorParser.ContinueStmtContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>ReturnStmt</c>
	/// labeled alternative in <see cref="AnalizadorParser.dcl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitReturnStmt([NotNull] AnalizadorParser.ReturnStmtContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>SliceIndex</c>
	/// labeled alternative in <see cref="AnalizadorParser.dcl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSliceIndex([NotNull] AnalizadorParser.SliceIndexContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>SliceAsign</c>
	/// labeled alternative in <see cref="AnalizadorParser.dcl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSliceAsign([NotNull] AnalizadorParser.SliceAsignContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>FuncCallStmt</c>
	/// labeled alternative in <see cref="AnalizadorParser.dcl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFuncCallStmt([NotNull] AnalizadorParser.FuncCallStmtContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>AsignStmt</c>
	/// labeled alternative in <see cref="AnalizadorParser.dcl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAsignStmt([NotNull] AnalizadorParser.AsignStmtContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>VarDeclStmt</c>
	/// labeled alternative in <see cref="AnalizadorParser.dcl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitVarDeclStmt([NotNull] AnalizadorParser.VarDeclStmtContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>BlockStmt</c>
	/// labeled alternative in <see cref="AnalizadorParser.dcl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitBlockStmt([NotNull] AnalizadorParser.BlockStmtContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>ExprStmt</c>
	/// labeled alternative in <see cref="AnalizadorParser.dcl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitExprStmt([NotNull] AnalizadorParser.ExprStmtContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="AnalizadorParser.sliceDcl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSliceDcl([NotNull] AnalizadorParser.SliceDclContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="AnalizadorParser.forID"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitForID([NotNull] AnalizadorParser.ForIDContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="AnalizadorParser.caseList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCaseList([NotNull] AnalizadorParser.CaseListContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="AnalizadorParser.caseStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCaseStmt([NotNull] AnalizadorParser.CaseStmtContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="AnalizadorParser.block"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitBlock([NotNull] AnalizadorParser.BlockContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="AnalizadorParser.varDcl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitVarDcl([NotNull] AnalizadorParser.VarDclContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="AnalizadorParser.varAsign"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitVarAsign([NotNull] AnalizadorParser.VarAsignContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="AnalizadorParser.varCall"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitVarCall([NotNull] AnalizadorParser.VarCallContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="AnalizadorParser.parametros"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitParametros([NotNull] AnalizadorParser.ParametrosContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="AnalizadorParser.param"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitParam([NotNull] AnalizadorParser.ParamContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="AnalizadorParser.args"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitArgs([NotNull] AnalizadorParser.ArgsContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>Corchetes</c>
	/// labeled alternative in <see cref="AnalizadorParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCorchetes([NotNull] AnalizadorParser.CorchetesContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>IncrementoDecremento</c>
	/// labeled alternative in <see cref="AnalizadorParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitIncrementoDecremento([NotNull] AnalizadorParser.IncrementoDecrementoContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>Or</c>
	/// labeled alternative in <see cref="AnalizadorParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitOr([NotNull] AnalizadorParser.OrContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>AddSub</c>
	/// labeled alternative in <see cref="AnalizadorParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAddSub([NotNull] AnalizadorParser.AddSubContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>Parens</c>
	/// labeled alternative in <see cref="AnalizadorParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitParens([NotNull] AnalizadorParser.ParensContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>Relational</c>
	/// labeled alternative in <see cref="AnalizadorParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitRelational([NotNull] AnalizadorParser.RelationalContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>SliceDeclStmt</c>
	/// labeled alternative in <see cref="AnalizadorParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSliceDeclStmt([NotNull] AnalizadorParser.SliceDeclStmtContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>ExpChar</c>
	/// labeled alternative in <see cref="AnalizadorParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitExpChar([NotNull] AnalizadorParser.ExpCharContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>ExpInteger</c>
	/// labeled alternative in <see cref="AnalizadorParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitExpInteger([NotNull] AnalizadorParser.ExpIntegerContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>Not</c>
	/// labeled alternative in <see cref="AnalizadorParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitNot([NotNull] AnalizadorParser.NotContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>AccesoSlice</c>
	/// labeled alternative in <see cref="AnalizadorParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAccesoSlice([NotNull] AnalizadorParser.AccesoSliceContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>MulDivMod</c>
	/// labeled alternative in <see cref="AnalizadorParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitMulDivMod([NotNull] AnalizadorParser.MulDivModContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>Identifier</c>
	/// labeled alternative in <see cref="AnalizadorParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitIdentifier([NotNull] AnalizadorParser.IdentifierContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>AsigAddSub</c>
	/// labeled alternative in <see cref="AnalizadorParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAsigAddSub([NotNull] AnalizadorParser.AsigAddSubContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>And</c>
	/// labeled alternative in <see cref="AnalizadorParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAnd([NotNull] AnalizadorParser.AndContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>Negate</c>
	/// labeled alternative in <see cref="AnalizadorParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitNegate([NotNull] AnalizadorParser.NegateContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>ExpDouble</c>
	/// labeled alternative in <see cref="AnalizadorParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitExpDouble([NotNull] AnalizadorParser.ExpDoubleContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>IgualDesigual</c>
	/// labeled alternative in <see cref="AnalizadorParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitIgualDesigual([NotNull] AnalizadorParser.IgualDesigualContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>ExpBoolean</c>
	/// labeled alternative in <see cref="AnalizadorParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitExpBoolean([NotNull] AnalizadorParser.ExpBooleanContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>ExpString</c>
	/// labeled alternative in <see cref="AnalizadorParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitExpString([NotNull] AnalizadorParser.ExpStringContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>FuncCallExpr</c>
	/// labeled alternative in <see cref="AnalizadorParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFuncCallExpr([NotNull] AnalizadorParser.FuncCallExprContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="AnalizadorParser.tipo"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTipo([NotNull] AnalizadorParser.TipoContext context);
}
} // namespace analyzer
